### ISSUE TITLE
Build Custom Jupyterlab Image and Rocker RStudio image

### ISSUE THREAD

**Issue by Collinbrown95** [PHACDataHub/infra-core#34]
# Description

The idea is to build + scan a [custom vertex workbench image](https://cloud.google.com/vertex-ai/docs/training/create-custom-container) image in GitHub actions, push the image to artifact registry, and use the custom image instead of the default image.
```[tasklist]
### Tasks
- [ ] https://github.com/PHACDataHub/infra-core/issues/52
- [ ] https://github.com/PHACDataHub/infra-core/issues/53
- [ ] https://github.com/PHACDataHub/infra-core/issues/51
```

**Comment by Collinbrown95** [comment]
Closed by https://github.com/PHACDataHub/infra-core/pull/55
