### ISSUE TITLE
Storage RBAC explanation - what principals/roles are used in accessing GCS bucket data?

### ISSUE THREAD

**Issue by Collinbrown95** [PHACDataHub/infra-core#44]
```[tasklist]
### Tasks
- [x] List available persona interacting with the buckets.
- [x] What security features do we enable in the bucket (e.g. public access prevention, data versioning, etc.)
- [x] Data upload/download procedures, some of this is policy/boundary of the system and delegated to manual procedures (e.g. only access GCP console from work device on VPN)
```
