### ISSUE TITLE
Documentation for RStudio Workstation and Notebook Security items

### ISSUE THREAD

**Issue by Collinbrown95** [PHACDataHub/infra-core#45]
```[tasklist]
### Tasks
- [x] How do we run CVE scans on built images (e.g. trivy in GH workflow)
- [x] How do we build these images internally *after* the CVE scan is complete (e.g. tag, cloud build trigger, etc.)
- [x] Which upstream images do we use?
- [ ] ~~What modifications do we make (if any) to the upstream images?~~ (this should be a project-specific concern and not part of the general template)
```
