### ISSUE TITLE
GCP Deprecating User Managed and GCP Managed Notebooks in Favour of Notebook Instances

### ISSUE THREAD

**Issue by Collinbrown95** [PHACDataHub/infra-core#65]
# Description

As per [GCP's user managed notebook documentation](https://cloud.google.com/vertex-ai/docs/workbench/user-managed/introduction?_ga=2.73551634.-1227362694.1705696566), user managed notebooks and managed notebooks are going to be deprecated as of January 30, 2025.

At the time of creating this issue, the [GCP Terraform Provider](https://registry.terraform.io/providers/hashicorp/google/latest/docs) does not appear to support notebook instances yet. Once this is supported in Terraform, we will need to refactor the terraform module in the vertex template to replace user managed notebooks with notebook instances.

Since [GCP cloud workstations]() offer much of the same functionality as the vertex workbench product, the decision is to remove vertex notebooks from the template in favour of cloud workstations.

## TODO

- [ ] Update [various architecture diagrams](https://github.com/PHACDataHub/infra-core/tree/vertex-template/vertex-workbench-template) to reflect that vertex workbench notebooks are removed.
    - [x] README.md diagram
    - [ ] networking diagram
- [x] Remove all terraform components related to vertex workbench notebooks.
- [x] Remove jupyterlab image from tb-safe-inputs (implemented in https://github.com/PHACDataHub/tb-safe-inputs/pull/59 and https://github.com/PHACDataHub/tb-safe-inputs/commit/987378521d9d2586e087b6e2538f095f08636199)
- [ ] Test that everything works correctly after deprecating various components
